import{a as C,S as H,i as p}from"./assets/vendor-bad0427b.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&l(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function l(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const R=document.querySelector(".form"),f=document.querySelector(".input-text"),n=document.querySelector(".load-btn"),d=document.querySelector(".gallery"),u=document.querySelector(".loading-container");let s=1,g=40,c="",y=0;const m=C.create({baseURL:"https://pixabay.com/api/",params:{key:"41688461-d2a05e0fbe969f7f46dd1fb4f",q:"",image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:g}});function E(){return document.querySelector(".gallery-list").getBoundingClientRect().height}function P(r){window.scrollBy({top:r,behavior:"smooth"})}async function h(r){try{const o=await m.get("",{params:r}),{hits:i,totalHits:l}=o.data;if(i.length>0){const e=i.reduce((a,{largeImageURL:b,webformatURL:x,tags:L,likes:S,views:q,comments:v,downloads:w})=>a+`
                <li class='gallery-list'>
                    <a href='${b}'>
                     <img class='img-element' src='${x}' alt='${L}'/>
                     <div class='gallery-text-wrapper'>
                     <p>Likes: <span class='img-text'>${S}</span></p>
                     <p>Views: <span class='img-text'>${q}</span></p>
                     <p>Comments: <span class='img-text'>${v}</span></p>
                     <p>Downloads: <span class='img-text'>${w}</span></p>
                     </div>
                    </a>
                </li>`,"");if(d.insertAdjacentHTML("beforeend",e),new H(".gallery a",{captionType:"attr",captionsData:"alt",captionDelay:250,captionPosition:"bottom",close:!0,enableKeyboard:!0,docClose:!0}).refresh(),s+=1,n.style.display="flex",s>2){const a=E();P(2*a)}y=l,s>=Math.ceil(y/g)&&(n.style.display="none",p.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."}))}else p.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}),n.style.display="none"}catch(o){p.error({title:"Error",message:o.message,position:"topRight"})}finally{u.style.display="none"}}function $(){c=f.value.trim();const r=new URLSearchParams({...m.defaults.params,page:s,q:c});u.style.display="flex",n.style.display="none",h(r)}n.addEventListener("click",$);R.addEventListener("submit",r=>{r.preventDefault(),d.innerHTML="",d.innerHTML===""&&(u.style.display="flex"),s=1,c=f.value.trim(),n.style.display="none";const o={...m.defaults.params,q:c,page:s};h(o)});
//# sourceMappingURL=commonHelpers.js.map
